### ISSUE TITLE
Wrong filter of group while open edit window

### ISSUE THREAD

**Issue by Schrolli91** [nielsfaber/scheduler-card#314]
When i open the edit window i have some wrong group filtering (show me the schedule entities).
If i switch to another group and then back it is ok.

Video will show that behavior better than my words can do it ;-)
https://user-images.githubusercontent.com/6043382/105408236-fc88b200-5c2e-11eb-8087-94ced7e60a9d.mp4

used Version: v2.0.5

**Comment by KTibow** [comment]
What's your config?

**Comment by Schrolli91** [comment]
Which Information do you want?
The settings for this particular scheduler event is visible in the video.

**Comment by nielsfaber** [comment]
For me the problem is clear, I just didn’t have  time to dive into it. Sorry

**Comment by Schrolli91** [comment]
Thats not critical for me but maybe you can give me a hint whats wrong and i will try to fix it myself and will provide this via PR.

**Comment by nielsfaber** [comment]
> maybe you can give me a hint whats wrong and i will try to fix it myself

I think its not very trivial to fix, for someone other than myself.
Here's where the list of entities per group is composed:
https://github.com/nielsfaber/scheduler-card/blob/main/src/custom-elements/scheduler-entitypicker-card.ts#L66
Feel free to investigate, but may cause headaches..

**Comment by nielsfaber** [comment]
This should be fixed in https://github.com/nielsfaber/scheduler-card/commit/3963a4c6bd62aab6c441b2f1f67bb5c68e915947
It will be included in the upcoming release.

**Comment by Schrolli91** [comment]
Thanks for your efforts so far :-)

**Comment by nielsfaber** [comment]
I am closing the issue, assuming this is fixed now.
Please shout if you still have problems with recent releases of the card 🙂

**Comment by Schrolli91** [comment]
Maybe i doing something wrong?
But if i edit it, i still see some wrong entities.
![image](https://user-images.githubusercontent.com/6043382/118386962-7d731b80-b61b-11eb-886e-246de90b38b8.png)

If i will click on the explicit group its ok.
![image](https://user-images.githubusercontent.com/6043382/118386970-8ebc2800-b61b-11eb-9aa7-9fa4e9ccb9c6.png)

I only see this behavior when the "mehrere" (multiple) is activated.

**Comment by nielsfaber** [comment]
You were right, I don't know what I fixed about it, but the same problem showed up for me.
I made yet another fix, I think this time it will be OK finally.
