### ISSUE TITLE
Service variables not showing up

### ISSUE THREAD

**Issue by marcelpetersen** [nielsfaber/scheduler-card#996]
### Checklist

- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v4.0.5

### Component Version

v3.3.8

### Bug description

I noticed that my custom variables for my actions not showing up anymore in the ui.

Configuration:
```
type: custom:scheduler-card
tags: wohnzimmer
customize:
  climate.wohnzimmer:
    name: Heizung Wohnzimmer
    icon: mdi:thermometer
    actions:
      - service: script.set_temp
        variables:
          target_temperature:
            name: Temperatur
            min: 5
            max: 25
            step: 0.5
            unit: °C
          temporarily_disable_other_automations:
            name: Andere Automatisierungen währenddessen deaktivieren?
            options:
              - value: Nein
              - value: Ja
        service_data:
          target_climate: climate.wohnzimmer
          target_room: wohnzimmer
        name: Temperatur setzen
        icon: mdi:thermometer
```

Output:

<img width="559" height="577" alt="Image" src="https://github.com/user-attachments/assets/24ed8056-353f-4294-a520-f361522de19b" />

In old versions i should see here the options to select a temperature (target_temperature) and can choose a value for "temporarily_disable_other_automations". So it seems that my configurations doesnt have any effect anymore. I tried to figure out if anything changed, but without any result. 

### Steps to reproduce

Use this configuration:
```
type: custom:scheduler-card
tags: wohnzimmer
customize:
  climate.wohnzimmer:
    name: Heizung Wohnzimmer
    icon: mdi:thermometer
    actions:
      - service: script.set_temp
        variables:
          target_temperature:
            name: Temperatur
            min: 5
            max: 25
            step: 0.5
            unit: °C
          temporarily_disable_other_automations:
            name: Andere Automatisierungen währenddessen deaktivieren?
            options:
              - value: Nein
              - value: Ja
        service_data:
          target_climate: climate.wohnzimmer
          target_room: wohnzimmer
        name: Temperatur setzen
        icon: mdi:thermometer
```

**Comment by nielsfaber** [comment]
Could you please update to the v4.0.6 release and try again?
I made quite some improvements related to handling of custom actions, perhaps this issue has been resolved in the mean time.
Please let me know if the behaviour is still problematic or solved itself.

**Comment by marcelpetersen** [comment]
Unfortunately the problem is still present in 4.0.6

**Comment by nielsfaber** [comment]
I copied your `customize` configuration to my own setup for testing.
For me the variables show up as they should:

<img width="575" height="700" alt="Image" src="https://github.com/user-attachments/assets/509f60b7-d269-4e26-9924-b01979f4b418" />

The only issue I'm seeing is that the (fixed) service_data parameters are listed in each timeslot, doesn't look very useful.

Can you double-check that you are running version v4.0.6? See https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#checking-card-version for instruction.

**Comment by nielsfaber** [comment]
I made a small change (https://github.com/nielsfaber/scheduler-card/commit/7c172a3e09a047afaa56e23ec40f36709107c795) that causes only the selectable parameters to be shown in the timeslots:

<img width="550" height="700" alt="Image" src="https://github.com/user-attachments/assets/fb8658b6-77f1-4fa4-99d5-5486eb158144" />

**Comment by marcelpetersen** [comment]
I double checked and created a new card. With the new card it is working. My old card still doesnt show the variables but i think this is a different problem

**Comment by marcelpetersen** [comment]
Can confirm now that it is working!
